### ISSUE TITLE
Basic/Flex Landing Page

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#167]
No notes in Mural

[Figma Link](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=501%3A1276)

Fields:
- [x] (Node title should be renamed to "CMS Title")
- [x] Display Title (field_display_title) [Existing field]
- [x] Header (field_header) Paragraph, single value - **need to define paras later
- [x] Featured Image
- [x] Teaser / Short Description
- [x] Content (field_content) Paragraph, multi-value - **need to define all paras later

Migration Fields:
- [x] "Body (mig)" (field_mig_body) Long text and summary - Text area with a summary

<hr>
Needed Functionality:

- [x] Side bar/Menu (visually left)
  - [x] This will require some testing and preprocess of the content paragraphs. Content paragraphs will have to be defined as "sidebar section" or not. This could be hardcoded or maybe a paragraph group in the BE. (discuss with @pingevt )
- [ ] SEO defaults

**Comment by pingevt** [comment]
We may need to pull Header Image into its own Para.
