### ISSUE TITLE
Page Header Media - Full Bleed

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#195]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=424%3A1282)
Screenshot:

![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/ada7aed7-fd0d-4914-835d-7ac555f85543)

- [ ] ~~Header | field_header_text | Text | Text field~~
- [ ] ~~Subtitle | field_subtitle | Text | Text field~~
- [ ] Media | field_media | Media | Image
- [ ] CSS Classes | field_css_classes | Text | Text field

- Discuss.. do header and subtitle come from the component or the node... ?? Discuss amongst yourselves

**Comment by pingevt** [comment]
Combining with #196 and closing this issue.
