### ISSUE TITLE
Video Embed Para - BE

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#200]
[Figma Comp
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A3369)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/722ffcb9-e693-47b0-bf50-9b6932e59f06)

**Comment by pingevt** [comment]
I think we are going to call this Media embed... which can handle 1-offs of all media types.
