### ISSUE TITLE
Left/Right Feature

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#201]
Left/Right dictates where the text will be.

[Figma Comp
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A3385)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/69bca808-6904-4c56-becc-ea4a6f5b8c40)

- [x] Header | field_header_text | Text | Text field |  
- [x] Eyebrow | field_eyebrow | Text | Text field |  
- [x] Media | field_media | entity ref | Media:Image |  
- [x] Description | field_description | Long text | Text area (multiple rows) |  
- [x] CTA | field_cta | Link |   |  
- [x] CSS Classes | field_css_classes | Text | Text field |  
- [x] Options (fieldgroup)
- [x] Theme | field_theme |   |   | reference a taxonomy for themes
- [x] Header Options | field_header_style | Select | ??? |  
- [x] ~~Background Color | field_bg_color |   |   | reference a taxonomy for themes~~
- [x] CTA buttons for map and explore

**Comment by pingevt** [comment]
@pingevt the optional icons we can use for the link ctas... What are we calling those?

glyph?
icon?

**Comment by pingevt** [comment]
ok - icon/glyph may only be for the header... but we do need to button or not...

**Comment by maxfenton** [comment]
I need to expand the CTA object to include those button-with-icon types
