### ISSUE TITLE
Multi-Column Callout (Related Articles)

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#202]
[Figma Comp (2)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A2135)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/0d176469-46de-45be-abcf-dfb551b80b2b)
[Figma Comp (3)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A2624)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/9208f661-b024-488b-bccb-34f61c74a5e6)
[Figma Comp (4)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=526%3A2551)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/44a639b3-7d0c-4967-a388-b88bc712a6a1)
[Figma Comp (5+)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=756%3A1211)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/e3eb9045-9db3-4a76-be38-f0e09e2692b3)

- [x] Header	field_header_text	Text	Text field
- [x] CTA	field_cta	Link	
- [x] Cards		Cards Yo!
- [x] CSS Classes	field_css_classes	Text	Text field

**Comment by maxfenton** [comment]
Need to test with a CTA

**Comment by maxfenton** [comment]
@morganfoust On mobile screen sizes, do these cards stack or become a pseudo-carousel (overflow-x-auto with a scrollbar)?

**Comment by pingevt** [comment]
@maxfenton - `field_css_classes` is the text field they have to add classes to components. I think we have a ticket to go back and make sure these are all added.

**Comment by morganfoust** [comment]
@maxfenton These should stack on mobile
