### ISSUE TITLE
Subscribe Banner

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#203]
- [ ] BE
- [x] FE
- [x] Integration

---

## Visual QA
- [x] width at various breakpoints

---

We need to research how this is done on the old site.

<hr>

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A3409)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/d64b0961-6451-4f34-9d79-e03428e095fe)

**Comment by maxfenton** [comment]
- Current site pushes you to https://app.e2ma.net/app2/audience/signup/1903699/13210/ with the email address filled out on that page. 
- Fractal component does the same. Front-end styling is ready for visual QA. 
- Replaced genericon arrow with svg

**Comment by maxfenton** [comment]
While doing the footer signup, I realized there were _two_ Fractal components for this same thing and made sure all the templates are calling the correct one. 

I also removed a bunch of specific ID attributes that were also being used by the signup in the footer.

**Comment by maxfenton** [comment]
Looks good to me on `releases/flex-2.0`

**Comment by maxfenton** [comment]
Visual approval
