### ISSUE TITLE
Upcoming Events Sidebar

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#205]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=532%3A3065)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/f8d76d16-38ba-4ea1-b887-41670508bbc0)

**Comment by pingevt** [comment]
data currently getting kinted out

**Comment by maxfenton** [comment]
devcomplete!
