### ISSUE TITLE
Ticketing Table

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#209]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=538%3A2796)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/d312c4b8-1f77-47c2-9bd0-cad8508a7aeb)

**Comment by pingevt** [comment]
making new para component...
