### ISSUE TITLE
WYSIWYG with Sidebars

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#211]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=755%3A1414)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/1b626eb5-b83f-491c-a120-d9d835974aa6)

**Comment by pingevt** [comment]
This content in image is invalid

**Comment by pingevt** [comment]
never mind - closing
