### ISSUE TITLE
Sitewide Alert

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#213]
- [x] set height on desktop screens 
- [x] ~decide if above/below tan border~ remove tan top border if there is an alert
- [x] put it somewhere on small screens
- [x] add 64px additional padding to `main` if there is an alert

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A4393)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/a2af21ae-1838-4184-84d9-b8b15dfed453)

See #233 -- building Alerts as 1 content type

**Comment by pingevt** [comment]
@maxfenton Alerts added in above the menu like on current site - this does not seem optimal!

**Comment by maxfenton** [comment]
Yeah, that's a funny UX pattern, but oh well...

I spent some minutes convincing myself not to hate how it works on small screens so I can just let it go as-is.

I added a few cleanups — there's some arbitrary additional padding now on the page content if there's a global alert, and removed tan 8px header border when there's an alert
