### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#214]
We need to figure out how this gets implemented... 

Is it just styles for views?
Is it a para bundle?

1/28 - this is a para
Top-level paragraph is an accordion group and each item is an accordion item

<hr >

Fields:

Copy what we have from Amon Carter (or ask @pingevt for more info)

<hr >

Reference:

[Figma Comp
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A4491)Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/f319b752-d152-477c-bb7d-341338990aa3)

**Comment by pingevt** [comment]
1/28 - sprint planning meeting. Make it a para bundle!

**Comment by maxfenton** [comment]
Handing this off to @dlaufer 
Branch in progress is `feature/214-fe-accordion`

Figma reference:
https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A4491

**Comment by dlaufer** [comment]
@maxfenton Ok, saucepot accordion is integrated and working great. just needs some styling. 
![Screen Shot 2022-02-21 at 9 30 25 AM](https://user-images.githubusercontent.com/5403982/154975548-be958812-2a61-424b-a7da-11e529ab8bc4.png)
![Screen Shot 2022-02-21 at 9 30 17 AM](https://user-images.githubusercontent.com/5403982/154975560-8bc381cc-47bd-4c61-9612-51d80ac02d05.png)

**Comment by dlaufer** [comment]
@maxfenton got it working in fractal :)

**Comment by maxfenton** [comment]
Updated in `release/flex-2.0`
<img width="857" alt="Screen Shot 2022-02-21 at 6 02 46 PM" src="https://user-images.githubusercontent.com/906502/155036028-92116db8-31ce-4172-9007-fb3f917f5b8c.png">
