### ISSUE TITLE
List Block

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#215]
We need to figure out how this gets implemented... 

Is it just styles for views?
Is it a para bundle?

Use case: https://longwoodgardens.org/news/in-the-news

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A4511)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/15cb6335-1db7-4126-a559-5b3ac4d5e6b9)

**Comment by pingevt** [comment]
1/28 - still figuring out

**Comment by BSBaker2** [comment]
news/press view - no need for paragraph
