### ISSUE TITLE
Instagram Grid

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#217]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A4666)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/888c2094-0fca-4b79-8a8d-c8427eea215d)

**Comment by pingevt** [comment]
closing in favor of #336
