### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#222]
For this we should probably just use the Drupal templates for this as the Drupal templates usually handle a lot for this component. BE should get this setup on the Drupal side and then Discuss with FE.

<hr>

- [ ] Templates set-up in Drupal and Longwood theme.
- [ ] Discuss with FE how to implement classes/markup.

<hr>

References:

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=431%3A4900)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/836d2179-027e-4eee-8d0e-16b44c2e46ef)

**Comment by pingevt** [comment]
closing in favor of #239
