### ISSUE TITLE
Homepage Hero

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#226]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=433%3A5423)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/c18156aa-7e67-45c1-a634-9941dbd7a7a5)

**Comment by maxfenton** [comment]
Moved to duplicate #409

**Comment by pingevt** [comment]
@maxfenton BE should be done - let me know if you need any help with hooking it up.
