### ISSUE TITLE
Blog Landing Header - FE

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#227]
Per Blog Sprint Kickoff + Search Sprint Kickoff - We are removing blog-specific search and the Longwood team will rely on Global Search to find blog posts.

Check with Morgan/Pete on retaining Category filtering?

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=433%3A5480)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/59736908-7ce1-4ecc-9c82-2aaf163ae076)

**Comment by maxfenton** [comment]
@dlaufer This fractal component is in `cms/web/themes/custom/longwood/fractal/patterns/06-components/blog-landing-header/blog-landing-header.twig` — we should talk about how the loop through Categories works if this markup doesn't work for you.
