### ISSUE TITLE
Blog - All Articles Listing - FE (Needs markup marrying)

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#229]
Design: https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=1707%3A1884

Description: this should be driven by a view. And #288 is part of this ticket. Lets keep that open for now, just know this is combined.

We'll need to re-use this for category pages.

Open Question: do categories each have their own page? Or just this page filtered?

<hr>

Functionality:

I would make this a separate paragraph. (Currently with no fields) We preprocess the para, we can pull in the view.

The view will need the exposed form to handle the Category filter.

- [x] no ajax pagination
- [x] no ajax (to start)

<hr>

Reference:

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=545%3A2828)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/ecf85925-e197-4136-bfc7-615b096532dd)

**Comment by dlaufer** [comment]
@maxfenton this also could use a little front-end marriage, too.

**Comment by maxfenton** [comment]
@dlaufer I think I cleaned this up, but let me know

**Comment by pingevt** [comment]
looking good -minus pagination which is in this ticket: #239
