### ISSUE TITLE
Sponsor Block

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#231]
From our Morgan: We should force to greyscale.

[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=547%3A2831)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/334c2325-ce04-4261-b228-228b72922414)

- [x] adjust width depending on where it is on a page

**Comment by maxfenton** [comment]
This should be ready after the next push of `release/flex-2.0`
