### ISSUE TITLE
Video Series

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#232]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=433%3A5652)

<hr>

do we need to have a description field? Or is the caption for the video oK?

<hr>

Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/c8f6caec-8277-493a-aebd-943bb7e9eecf)

**Comment by maxfenton** [comment]
@pingevt The larger text is coming through from the videos as a caption, but I don't know where to get that smaller text

**Comment by pingevt** [comment]
Oh - I was thinking the large text is the media name and the small text is the caption

**Comment by maxfenton** [comment]
Oh! That makes sense.

**Comment by maxfenton** [comment]
@pingevt Are there any captions being passed in `{{ content.field_videos }}`` ?
