### ISSUE TITLE
Countdown Counter

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#236]
[Figma Comp
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=561%3A3349)Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/871e0ff2-87ae-43a2-b8e3-8f29189755d1)

- [x] Target Date | field_target_date | Date | Pop-up calendar
- [x] Message Until | field_message_until | Long text | Text area (multiple rows)
- [x] Message After | field_message_after | Long text | Text area (multiple rows)

**Comment by pingevt** [comment]
Question: Should it be 1 day until tomorrow or 0 days until tomorrow?

**Comment by yasmeenfahmy** [comment]
1 day until tomorrow. 0 days if it's the day-of.

**Comment by pingevt** [comment]
@pingevt - fix math

**Comment by pingevt** [comment]
@maxfenton verify and signoff

**Comment by maxfenton** [comment]
Looks good to me.
