### ISSUE TITLE
Standalone Audio

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#237]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=561%3A3375)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/9f2285f0-a397-4e12-96b3-8d0830ed23b9)

Look at existing audio style and make changes to look like new Figma design (if possible)

**Comment by maxfenton** [comment]
I added sample content to https://live-longwood-d8-cms.pantheonsite.io/flex-components-preview and need to know what to do within the block. 

I think:
- [ ] center the audio player
- [ ] format the caption to look like a caption ... _should it also be centered_
