### ISSUE TITLE
Blog Listing - Pagination

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#239]

**Comment by pingevt** [comment]
@maxfenton - this doesn't seem to be matching the figma - do we need to discuss?

**Comment by maxfenton** [comment]
Fixes made today to the Drupal pager template:
- "first" renamed to "1" and moved between "prev" and "left ellipsis" - only appears if "left ellipsis" exists
- "last" renamed to "[last page number (int)]" and moved between "next" and "right ellipsis" - only appears if "right ellipsis" exists
- padding on page number adjusted to get closer to 14px wide underlines on single-digit links
- "prev" and "next" links changed to match figma button styles
- added `disabled` styles/markup for "prev" on first page and "next" on last page

**Comment by pingevt** [comment]
Looking good, thanks!
