### ISSUE TITLE
Blog Author Integration

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#245]
12/10 Sprint Planning: @pingevt will get Max a local version of this existing design on their live website. This can't be viewed on the live website currently because LWG is not using the CT.

Screenshot on #277

**Comment by maxfenton** [comment]
Images from Pete. Note these are not current design, but do model the content.
![screencapture-lwg7-local-author-pete-inge-2021-12-10-11_45_18](https://user-images.githubusercontent.com/906502/145612562-e93ce033-a9c6-404c-a41e-195df2f7c9f1.png)
![screencapture-lwg7-local-author-pete-inge-2021-12-10-11_44_53](https://user-images.githubusercontent.com/906502/145612572-c2df7e79-e86d-4044-a174-ba59822c941f.png)

**Comment by pingevt** [comment]
@dlaufer to verify all "real" data and functionality complete
