### ISSUE TITLE
Quote Integration

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#254]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A4681)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/1e05b953-7640-45bb-91ad-26e8f921daf3)

**Comment by maxfenton** [comment]
Setting up Fractal and base typography styles as part of this ticket, since it’s the first one.
