### ISSUE TITLE
WYSIWYG Para - FE

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#261]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A4347)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/196f1029-1de3-401f-9ea7-e568c3e80af2)

Example pages:
- https://live-longwood-d8-cms.pantheonsite.io/flex-components-preview
- https://live-longwood-d8-cms.pantheonsite.io/blog/2022-01-06/test-blog

Style:
- [x] media paragraph
- [x] wysiwyg paraghraph
- [x] wysiwyg paragraph images (left/right/center)
- [x] legacy styles
- [x] media positioning

**Comment by pingevt** [comment]
We need more content!

**Comment by pingevt** [comment]
@maxfenton - i think we need to "support" these legacy styles to a certain degree from the WYSIWYG. If we can keep them in a separate css or sass file so we can easily get rid of some of these at some point, that would be awesome.

Do we have a "legacy css" file?

```
p.caption|Caption (legacy)
table.responsive-table|Responsive Table (legacy)
tr.table-header-row|Table Header Row (legacy)
p.quick-links|Quick Links (legacy)
p.hidden|Hidden (legacy)
h2.no-border|No bottom border (h2) (legacy)
span.no-border|No bottom border (span) (legacy)
th.with-helper|Table Cell With Helper (legacy)
table.standard|Standard Table (legacy)
div.blockquote|Block Quote (legacy)
p.intro|Intro (legacy)
p.alpha|Alpha (legacy)
p.beta|Beta (legacy)
p.gamma|Gamma (legacy)
p.delta|Delta (legacy)
p.epsilon|Epsilon (legacy)
p.zeta|Zeta (legacy)
p.eta|Eta (legacy)
p.theta|Theta (legacy)
p.iota|Iota (legacy)
p.kappa|Kappa (legacy)
p.lamda|Lambda (legacy)
p.mu|Mu (legacy)
p.caption|Caption Image (legacy)
p.caption-right|Right Caption Image (legacy)
p.caption-right-outdent|Right Outdent Caption Image (legacy)
span.more|More (legacy)
p.violet|Violet Bg (legacy)
p.green|Green Bg (legacy)
p.red|Red Bg (legacy)
p.amber|Amber Bg (legacy)
p.tan|Tan Bg (legacy)
p.brown|Brown Bg (legacy)
p.blue|Blue Bg (legacy)
p.pink|Pink Bg (legacy)

```

**Comment by maxfenton** [comment]
@pingevt Sure thing — is it possible to make a test post that has some/all of that content in it for testing?

**Comment by pingevt** [comment]
working on it!

**Comment by maxfenton** [comment]
These new/legacy classes are in progress. Colors and the paragraphs should be in place. 
Tables: not yet.

Big question s whether to normalize these greek styles → new/current typography or just implement as-is. (Starting with "as-is")

**Comment by pingevt** [comment]
I'm fine with holding off on tables for a later date (just make a ticket to track)

I'd say as-is assuming that is easer / more time efficient?

**Comment by maxfenton** [comment]
I copied over some basic CSS from the existing styles (15min) and I think this should move to the icebox and become a Visual QA ticket for once content that has these is in place.
