### ISSUE TITLE
Image Grid Callout Para - FE

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#262]
[Figma Comp](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=755%3A1279)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/a591dd76-51af-44cc-aa65-de2be2663dfd)

**Comment by maxfenton** [comment]
Component is in `patterns/06-components/image-grid-callout/image-grid-callout.twig` and includes the objects `card` and `card--featured`
