### ISSUE TITLE
Blog Feature - Para Bundle - FE

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#265]

**Comment by maxfenton** [comment]
<img width="397" alt="Screen Shot 2022-02-09 at 10 12 19 AM" src="https://user-images.githubusercontent.com/906502/153229947-29816c8c-1a56-4c8d-ada7-30945b025e07.png">

**Comment by maxfenton** [comment]
→ https://live-longwood-d8-cms.pantheonsite.io/flex-components-preview
