### ISSUE TITLE
Related Posts (View) - FE

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#270]

**Comment by maxfenton** [comment]
Related posts uses the `Multi-column Callout` component in `patterns/06-components/multi-column-callout/multi-column-callout.twig` with data similar to the `Blog Detail` page: `patterns/07-layouts/blog-detail/blog-detail.config.js`

**Comment by maxfenton** [comment]
Looks good to me on https://live-longwood-d8-cms.pantheonsite.io/blog/2022-01-06/test-blog
