### ISSUE TITLE
WYSIWYG - Anchors

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#274]
From Pete: "Anchor links to jump within the page. I think its a mixture of Linkit and the available attributes in the Link dialog. Create links and also link to them."

I believe this may help:
https://www.drupal.org/project/anchor_link

**Comment by dlaufer** [comment]
Done.
![Screen Shot 2022-02-17 at 11 13 19 AM](https://user-images.githubusercontent.com/5403982/154523566-9f8ed9e3-bda3-4eb3-aa55-3884577fe431.png)
![Screen Shot 2022-02-17 at 11 12 35 AM](https://user-images.githubusercontent.com/5403982/154523568-c75cb6e7-bdae-4cf8-b913-6c46948bfb9a.png)

**Comment by dlaufer** [comment]
@yasmeenfahmy @pingevt the new flag button in the WYSIWYG lets you create an anchor tag.
