### ISSUE TITLE
Blog Landing Header - FE (marry filter dropdown markup)

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#288]
NO SEARCH! - but filter

- [x] BE
- [x] FE
- [ ] Integration

**Comment by dlaufer** [comment]
@maxfenton this is integrated on the backend, however I'm dumping the dropdown filter from Drupal and commented out the filter markup you had. So it needs some marrying with your frontend.

**Comment by pingevt** [comment]
this looks good to me for now
