### ISSUE TITLE
Seasonal Management

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#291]
I made some assumptions here:

- Confirmed: always 5 seasons
- Confirmed: if we are in between seasons, for functionality that requires a seasons, ~we fall back to the previous season~ we use the next upcoming season per JF on 2/11.

Affects (on Garden Pages only)
- Social share image
- Hero image (not video)
- Set the lead image in "Stroll Through the Seasons" Gallery

Override with Featured Media if they add a video.

**Comment by yasmeenfahmy** [comment]
@pingevt an update on this one, Jen confirmed on Friday that during season gaps the CMS should use the next upcoming season, not the previous one. I've updated the description.
