### ISSUE TITLE
WYSIWYG Image text fields

### ISSUE THREAD

**Issue by dlaufer** [bluecadet/longwood-d8#295]
This page has WYSIWYG images with captions that didn't carry over...

https://longwoodgardens.org/blog/2021-10-27/new-forms-new-displays-new-fun

![Screen Shot 2022-01-21 at 12.49.10 PM.png](https://images.zenhubusercontent.com/5d81058c9e6efa0001037aad/9ae59215-e673-4f80-a648-48634fa50b67)

And on the new site, it showed this:

![Screen Shot 2022-01-21 at 12.53.25 PM.png](https://images.zenhubusercontent.com/5d81058c9e6efa0001037aad/c5ac0a9e-0bd5-44f6-b4b7-de04f3500b69)

(although i have put content in this image now, to test it, but the other WYSIWYG images on the page are similar: https://live-longwood-d8-cms.pantheonsite.io/media/42681/edit?destination=/admin/content/media%3Fname%3D531179%26type%3DAll%26status%3DAll%26langcode%3DAll%26mt%3DAll)

![Screen Shot 2022-01-21 at 12.56.23 PM.png](https://images.zenhubusercontent.com/5d81058c9e6efa0001037aad/ae3669c8-57fb-4fc1-b9c5-c0334a0f0e14)

D8 - Migrated page -> https://live-longwood-d8-cms.pantheonsite.io/node/417/edit

**Comment by pingevt** [comment]
ok - 2 things here...

1. This is a new pattern for caption. Without a specific span around the caption...
2. When we embed images in the WYSIWYG from d7, the captions are in the WYSIWYG, NOT on the media element. When rendering the Media in WYSIWYG display modes, we need to check for those data attrs.

Hopefully will re-run blog migration monday morning and this will be updated
