### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#306]
We may need design input on this, but should see how they are currently handling it.

@yasmeenfahmy: There seem to be 2 versions? 

https://longwoodgardens.org/404
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/76a1d69a-64cd-4995-80d3-8bf71a988a89)

https://longwoodgardens.org/joke
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/fda2257b-0e8d-4e65-98f0-ee6e689b3376)

**Comment by maxfenton** [comment]
Current 404:

<img width="1629" alt="Screen Shot 2022-02-09 at 10 33 46 AM" src="https://user-images.githubusercontent.com/906502/153234166-eaa68469-0a1f-4af4-8630-7dcd89c19a7d.png">

**Comment by pingevt** [comment]
closing in favor of #371
