### ISSUE TITLE
Should we have local video for backgrounds?

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#312]
Time box to 20mins!

**Comment by pingevt** [comment]
use plyr/vidstack

**Comment by maxfenton** [comment]
Looking at plyr.io and https://bc-sauce.netlify.app/components/detail/ambient-video--width-audio-icon.html

**Comment by maxfenton** [comment]
I talked to Shaun about the saucepot ambient video component. He says it works well.

- limited to local video
- recommendation is 8 second clips
- ask Devon about video compression if need be

Does that work for the header?
Can we / should we limit hero background video to local files? 

Is hero video a new feature? Are we migrating any videos up there that are not local video?

**Comment by maxfenton** [comment]
And these are Jason's notes about improvements that Saucepot component needs: https://github.com/bluecadet/saucepot/issues/99
