### ISSUE TITLE
Blog View - Filter to wrong page

### ISSUE THREAD

**Issue by dlaufer** [bluecadet/longwood-d8#317]
The only BE/logic issue outstanding for the blog landing page is when you change filters, since it's a Page display of the view, it goes to the Page url set for the view. It needs to not do that. However, when you use a block view display, you need AJAX for the exposed filter to work. What view display should this be?
![Screen Shot 2022-02-01 at 6 15 10 PM](https://user-images.githubusercontent.com/5403982/152067480-ce7f20f3-3f06-4ba2-9c5b-ed7aa7d6f1ae.png)
![Screen Shot 2022-02-01 at 6 15 25 PM](https://user-images.githubusercontent.com/5403982/152067526-b88b33e0-03e3-4e8b-ac70-7943bc4018ad.png)

**Comment by dlaufer** [comment]
@pingevt only remaining logic issue for the blog landing.

**Comment by pingevt** [comment]
@dlaufer - If its a block with no page display, it just submits tot he current page
