### ISSUE TITLE
Sponsors - Image styles

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#323]
I believe there are currently 2 image styles created specifically for the Sponsor Images. Double check that both are using the "desaturate" or whatever plugin to make them B&W logos

**Comment by dlaufer** [comment]
Done. The sponsors_lg was missing the desaturate effect
<img width="593" alt="Screen Shot 2022-02-17 at 11 56 32 AM" src="https://user-images.githubusercontent.com/5403982/154532862-7e4a5f3b-bb98-499d-8bb6-b6b7877a5b01.png">
<img width="597" alt="Screen Shot 2022-02-17 at 11 56 27 AM" src="https://user-images.githubusercontent.com/5403982/154532865-aee1c637-b4de-4e22-bd67-a670b03fcfe1.png">

<img width="690" alt="Screen Shot 2022-02-17 at 11 56 58 AM" src="https://user-images.githubusercontent.com/5403982/154532879-f5c0d427-b764-4eb4-8134-c9ac8a807642.png">
.
