### ISSUE TITLE
Design QA: Floating "Our Blog" on Blog Listing

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#334]
Visit https://live-longwood-d8-cms.pantheonsite.io/blog?cat=3940 and scroll to the bottom to see (left of pagination)

Also noticed it on this Slideshows page so maybe it's the same thing? https://live-longwood-d8-cms.pantheonsite.io/test-slideshows

Browser/OS: 
Chrome on Windows 10 Desktop

Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/9dc3500a-7315-48ba-ab17-70f97c10d0f3)

<hr>

Todo:

- [x] Remove "Display Title" and "Page Subtitle" fields from the Full display mode of Flex page?

**Comment by pingevt** [comment]
This should be fixed first with the display formatter for Flex page. Then secondarily in the node tpl file

**Comment by dlaufer** [comment]
@maxfenton @pingevt Fixed this :)

**Comment by pingevt** [comment]
Thanks @dlaufer !

Can we also remove "Display Title" and "Page Subtitle" fields from the Full display mode of Flex page?

**Comment by dlaufer** [comment]
@pingevt donezo the right way

**Comment by pingevt** [comment]
WOW - my bad on this one... we do need to keep them in for the header part... 

NOTES:

- The header is pulling them in and rendering based on the full display mode so they are properly getting rendered.
- Fixed outside of this ticket...
sorry
