### ISSUE TITLE
Design QA: Caption for 1st Gallery Image Doesn't Appear on Load

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#335]
Here's the page I'm testing this on: https://live-longwood-d8-cms.pantheonsite.io/test-slideshows

Browser/OS: Chrome on Windows 10 Desktop

Page on load: 
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/98568c54-fd26-4b17-ab1a-3d03d3dc35d5)

If you navigate to the next Gallery item and then back the caption for the 1 image appears:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/8e3c1b13-f829-49f5-8701-4a068cb96348)

**Comment by maxfenton** [comment]
Fixed the JS
