### ISSUE TITLE
Blog Detail - bugs

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#339]
> Should there be a comma separating the categories when multiple categories are selected for a blog? Right now it's not.

<hr>

Is this FE or BE?

- [ ] Add commas between Categories.

**Comment by dlaufer** [comment]
Complete.
![Screen Shot 2022-02-17 at 9 21 38 AM](https://user-images.githubusercontent.com/5403982/154501042-d21058de-7a0a-43e6-9091-a2c3f32db481.png)
![Screen Shot 2022-02-17 at 9 21 35 AM](https://user-images.githubusercontent.com/5403982/154501044-98ed8630-8837-49e7-b604-0f2ce3ea3fe7.png)
