### ISSUE TITLE
Admin enhancements

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#340]
Content Page View:

- [x] Add "Authored On" column
- [x] Make content type filter multi-select.
  - original ask was to create a exclude dropdown, but with so many less content types. I think we keep it cleaner and if they don't like it we can add the exclude.
 - [x] remove language filter

**Comment by dlaufer** [comment]
@pingevt this is done, but I couldn't figure out how to get the sorting for "Authored On" to work on header click, like "Updated" does. It's the normal sort dropdown.
![Screen Shot 2022-02-11 at 12 49 15 PM](https://user-images.githubusercontent.com/5403982/153643098-d1439c00-9224-450c-9c4d-f663bc503d47.png)

**Comment by pingevt** [comment]
@dlaufer - if you go to the table settings, it will give you options to sort, etc for the table:
![Screen Shot 2022-02-14 at 4 52 12 PM](https://user-images.githubusercontent.com/3128823/153952734-f0c962b9-22bc-4a44-a841-7e3cdaea4a3b.png)
