### ISSUE TITLE
We need a Edit button for Media on a Node form

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#344]
Can we hook into `template_preprocess_media_library_item()` ?

<hr>

We need an easy way for Editors to edit Media they add to a node. The Media Library widget currently doesn't have a way to edit the media item. Lets see what we can do...

- [ ] setup a feature branch
- [ ] Add [Media Library Edit](https://www.drupal.org/project/media_library_edit) module
- [ ] Open up PR and get a multi-dev running
- [ ] Let's evaluate together!

Let me know when you get a multi-dev running and then lets walk through it.

Resource for link: https://git.drupalcode.org/project/media_library_edit/-/blob/8.x-1.x/media_library_edit.module

**Comment by dlaufer** [comment]
<img width="469" alt="Screen Shot 2022-02-16 at 2 06 38 PM" src="https://user-images.githubusercontent.com/5403982/154337715-57a5b596-53e7-4b64-b229-230842e20f44.png">

K, working. Edit shows up for all media library types, and crop only for images.
