### ISSUE TITLE
Admin Exp. Improvements

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#345]
@dlaufer 

- [x] Blog=>Related Blogs : Needs helper text
  - Related blogs will automatically populate with latest blogs with similar "Blog Category" Tags unless you manually choose some blogs here.
- [x] Blog=>Tease : Needs Helper text
  - Teaser will be used for callouts as well as the default for social media tags for description.
- [x] Flex Page=> Title CTA : update attributes
  - Should only have Target and Class, remove the other 2.
- [x] Each "top level" Paragraph should have a valid description
- [x] In Diff module settings turn off "Visual Inline" option. Our themes really screw this up.
- [ ] ~~Per Jen: **Add column to media library list that shows the number of times an asset is used**~~
- [x] Per Jen: Add "Edit" under Featured Image on blogs
- [x] Per Jen: Add caption, credit, and media tags for new image upload (in addition to alt text, which is already there)

<hr>

@yasmeenfahmy 

- [x] We need Images for each Paragraph Type (We should set some kind of standard for this)

**Comment by pingevt** [comment]
@dlaufer the media view usage added, was for the file, not the Media entity itself. Theres a separate ticket for that #308 which we can do later. Theres some weird aggregation stuff we need to do for it later on.

And we need to keep it open for @yasmeenfahmy 's tasks

**Comment by dlaufer** [comment]
@pingevt ah, my bad, i missed that task below that horizontal rule. i'll remove that column.

**Comment by dlaufer** [comment]
@yasmeenfahmy the list of paragraphs are here: https://live-longwood-d8-cms.pantheonsite.io/admin/structure/paragraphs_type. You can see one already has an icon image uploaded.
![Screen Shot 2022-02-18 at 11 22 30 AM](https://user-images.githubusercontent.com/5403982/154721887-780deceb-ff35-40ee-afb3-c26ee8f750e2.png)

You can add the image by clicking on the paragraph's dropdown and click on Edit.
![Screen Shot 2022-02-18 at 11 21 20 AM](https://user-images.githubusercontent.com/5403982/154722036-d294aa79-d4a0-48fc-b392-7ddcbb1459a5.png)

And you'll see the "Paragraph Type Icon" field. That's where you want to upload the screenshot of that paragraph.
![Screen Shot 2022-02-18 at 11 21 36 AM](https://user-images.githubusercontent.com/5403982/154722220-c332865e-1cdd-416d-84e9-e0ac8ce7b0e2.png)

**Comment by yasmeenfahmy** [comment]
I'm just dropping a note here that screenshots for paragraphs are done!
