### ISSUE TITLE
Add Admin Menu Across All Blogs

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#347]
This admin menu sporadically appears.

It's on this blog: https://live-longwood-d8-cms.pantheonsite.io/blog/2022-01-06/test-blog

But it's not on this blog: https://live-longwood-d8-cms.pantheonsite.io/blog/2021-11-03/now-time-fall-bulb-planting

![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/9298722b-e304-44fb-ae24-3e5f67568aae)

**Comment by pingevt** [comment]
@dlaufer - Can you take another look at this quick?

**Comment by dlaufer** [comment]
@yasmeenfahmy can you replicate this? I'm not able to replicate this. 

What user accounts was this seen on? Are you logging in as "admin"?

Gonna close this and we can reopen if we run into it again.
