### ISSUE TITLE
QA: WYSIWYG Image Not Taking Up Width of WYSIWYG

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#353]
The last image on this blog: https://live-longwood-d8-cms.pantheonsite.io/blog/2018-08-31/our-award-winning-orchid-collection

![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/05598c04-58e9-4d13-862f-8739b2d5cfc3)

**Comment by maxfenton** [comment]
That image is not that wide

**Comment by maxfenton** [comment]
I think images should never be scaled up beyond their actual image sizes, so in this case that image is just not wide enough. Ideally it would center, _but_ if we center it the `caption` would still left align to the content column and looks weird. So I went with left-aligned image (and ideally they will upload wider images)

**Comment by maxfenton** [comment]
For now: scale up to 100% of content column width
