### ISSUE TITLE
Map Views

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#355]
We need to start bringing over functionality for Maps. Lets start with the Map Views:

We need to migrate these with same names and machine names, etc. Map components are a bit different in the new site. They are no longer nodes, so we just need to be a little careful with that. If you run into any weirdness, let me know before going too far down the rabbit hole.

<hr>

- [ ] Map JSON Feed
- [ ] Map JSON Feed - Events
- [ ] Map JSON Feed - Slideshow

**Comment by BSBaker2** [comment]
using API instead
