### ISSUE TITLE
Video/Image Caption styles

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#356]
Looks like video captions are styled differently from images.

https://live-longwood-d8-cms.pantheonsite.io/blog/2021-10-12/artform-sashiko-luminary-form

<hr />

- [ ] confirm width of caption with @morganfoust

**Comment by maxfenton** [comment]
<img width="1437" alt="Screen Shot 2022-02-21 at 6 05 52 PM" src="https://user-images.githubusercontent.com/906502/155036240-893e7a21-b489-44db-8623-46474e81a551.png">

Good catch. I might need to also specifically add it for local media embeds. Need to check the various paragraph types.
