### ISSUE TITLE
"Header" Field styled correctly?

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#357]
> Flagging the header on the video embed on the blog. I'm not sure if it's formatted correctly

https://live-longwood-d8-cms.pantheonsite.io/blog/2021-10-12/artform-sashiko-luminary-form

**Comment by maxfenton** [comment]
@pingevt Is that supposed to be visible at all?

**Comment by maxfenton** [comment]
You're right! I missed that. It should be a H3

<img width="879" alt="Screen Shot 2022-02-21 at 5 40 13 PM" src="https://user-images.githubusercontent.com/906502/155034353-042a9ee1-4ef7-4c20-b587-917af1e16e62.png">

**Comment by maxfenton** [comment]
<img width="1437" alt="Screen Shot 2022-02-21 at 6 05 52 PM" src="https://user-images.githubusercontent.com/906502/155036350-43e5011e-f6e2-4045-bdce-3021ea72ba33.png">

Updated. And I need to double-check if that applied to `local` media as well as embedded.
