### ISSUE TITLE
Fonts.com and self-hosting fonts

### ISSUE THREAD

**Issue by maxfenton** [bluecadet/longwood-d8#358]
re: fonts.com — I created a new bundle of fonts on LWG’s account and 
- [ ] need to go over the weights/styles with Morgan when we walk through the site to make sure we’re covering the combinations the new design needs
- [x] reconsider how things like bold and italic are being styled in CSS _or_
- [x] ask Pete if (at a sysadmin level) we’re able to self-host these on Pantheon and meet [the security requirements](https://www.fonts.com/support/faq/how-to-self-host-web-fonts) of the license 
 
The short of it is: the fonts.com cdn serves each font style/weight as “normal/normal” with a separate font _name_ instead of serving the bold as `font-weight: bold` and the italic as `font-style: italic` 

In practice that means everywhere we would ordinarily say `font-weight: bold` we instead need to change the font family. It’s do-able but kindof a kludge. 

If we can self host then the `@font-face` declarations would be cleaner and we'd just need the async tracking code but not the CDN hosted versions, which I think would also be (maybe) more performant.

From the fonts.com faq above:

> Hosting our Web fonts on your own servers requires that you place reasonable security measures on them to prevent improper use. This generally includes the following:

- Keep the web font file names obfuscated (as they are provided, the provided sample CSS maps all the fonts to the correct files)
- Implement measures so that visitors may not easily download the web font files by simply typing the font file's URL into their browser (or by something like a basic wget command)
- Implement measures to that other web sites cannot "hot-link" to the font files hosted on your servers

I think in practice there's some nginx/htaccess trick to prevent direct downloads, but I don't remember. I also think people just skip that all the time, but there's some liability here, I guess.

**Comment by BSBaker2** [comment]
@maxfenton discussed in 2.22.22 status. Self host the fonts. We'll mention to LWG in a future meeting

**Comment by maxfenton** [comment]
Fonts are now self-hosted and the async code to keep track of traffic is in place.

**Comment by maxfenton** [comment]
<img width="1646" alt="Screen Shot 2022-03-17 at 3 37 46 PM" src="https://user-images.githubusercontent.com/906502/158882194-a920a49f-7c8a-4286-9b25-75be7bde8d6c.png">

Note: we are loading these font weights/styles
