### ISSUE TITLE
QA: Juicer Feature Square for IG

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#362]
Module is forcing a square but IG image is pulling in is rectangle so there's a gap.

![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/070e5142-1851-48e1-8f14-0420cbf39fc5)

**Comment by maxfenton** [comment]
Good catch. So, this is a featured image that is landscape. 

[Discussed this in Slack here](https://bluecadet.slack.com/archives/CSE5S75L0/p1645712107511029?thread_ts=1645711735.170159&cid=CSE5S75L0) 

My proposed (and implemented) solution is to make the blue background white. It will _appear_ to have a little extra bottom margin in this situation, but it’s good enough. 

<img width="1458" alt="Screen Shot 2022-02-24 at 9 15 09 AM" src="https://user-images.githubusercontent.com/906502/155544195-9c3d697a-9ea5-4be6-9ad5-5c98cdff50e3.png">

<img width="1415" alt="Screen Shot 2022-02-24 at 9 13 59 AM" src="https://user-images.githubusercontent.com/906502/155544164-3e4e99f4-6240-4d8e-8223-5a22b99634fa.png">
