### ISSUE TITLE
Blog Author - White space at top

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/longwood-d8#384]
Jen Google Table comment: On the blog author page, the "About the Author" and "Posts by ..." headlines are too tight with the top of the page

Need to define rule set

**Comment by maxfenton** [comment]
devcomplete

<img width="1642" alt="Screen Shot 2022-03-01 at 11 40 53 AM" src="https://user-images.githubusercontent.com/906502/156210731-c8c1c01b-2bd0-4f62-b338-c5aa3a24c7a3.png">
<img width="885" alt="Screen Shot 2022-03-01 at 11 41 05 AM" src="https://user-images.githubusercontent.com/906502/156210751-1e9ff6a2-0297-4016-a659-da037aa546b3.png">
