### ISSUE TITLE
BE: Hero (video) needs image fallback for motion-reduce and any video loading fail

### ISSUE THREAD

**Issue by maxfenton** [bluecadet/longwood-d8#406]
See note in `@fractal/06-components/hero/hero.twig`:
`{# TODO: replace with fallback image for motion-reduce and video fail-to-load #}`

- [x] Add video description for a11y
- ~see if there's a way to know if vimeo/youtube times out (maybe no)~
- [x] motion-reduce fallback image

**Comment by pingevt** [comment]
@maxfenton - I added changes to branch `feature/406-video-header`. let me know what you think or lets discuss
