### ISSUE TITLE
Related Events Paragraph Bundle

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#426]
similar to related events on District page

- [x] Header
- [x] List

Will show up here eventually: https://migcheck-longwood-d8-cms.pantheonsite.io/education/continuing-education

**Comment by maxfenton** [comment]
Updated styles

**Comment by maxfenton** [comment]
Confirmed that the width of this block is correct as-is. Adjusted hover/underline styles with Morgan.
