### ISSUE TITLE
Event Details Review (From Pete)

### ISSUE THREAD

**Issue by pingevt** [bluecadet/longwood-d8#435]
https://migcheck-longwood-d8-cms.pantheonsite.io/events-performances/events/floral-design-basics-online-class
https://longwoodgardens.org/events-performances/events/floral-design-basics-online-class

- [x] FE: "About this Class" - content label field needs more "prominence"
- [x] BE: Content label field should be above Description field

<hr>

https://migcheck-longwood-d8-cms.pantheonsite.io/events-performances/events/landscape-design-ii-class
https://longwoodgardens.org/events-performances/events/landscape-design-ii-class

- [x] BE/FE: Missing "Dates & Price" in right column sidebar
- [x] BE/FE: Related events needs title

<hr>

https://migcheck-longwood-d8-cms.pantheonsite.io/events-performances/events/valerie-june-performance
https://longwoodgardens.org/events-performances/events/valerie-june-performance

- [x] FE: "About this Performance" - content label field needs more "prominence"
- [x] FE: Anything (quick) we can do to make the embedded video full width?

<hr>

https://migcheck-longwood-d8-cms.pantheonsite.io/events-performances/events/fountain-performances
https://longwoodgardens.org/events-performances/events/fountain-performances

- [x] BE/FE: Missing "Dates & Price" in right column sidebar
- [x] BE: looks like empty Prices WYSIWYG

<hr>

https://migcheck-longwood-d8-cms.pantheonsite.io/events-performances/events/chrysanthemum-festival-event

- [ ] Causes a redirect to a flex page. How do we support this.
<hr>

- [x] BE: Add in CTA fields under prices
- [x] FE: Style new CTAs

**Comment by pingevt** [comment]
Empty "Price" WYSIWYGs are because there are HTML hidden text

**Comment by BSBaker2** [comment]
Causes a redirect to a flex page. How do we support this. might come back but not addressing if it does not
