### ISSUE TITLE
FE: back-end styling after webform is active

### ISSUE THREAD

**Issue by maxfenton** [bluecadet/longwood-d8#444]
After webform is active, some text on the admin side becomes un-readable. CSS is removed. Need to check and improve that.

https://live-longwood-d8-cms.pantheonsite.io/admin/structure/webform/manage/webform_263771

**Comment by pingevt** [comment]
https://longwoodgardens.org/content/test-pattern-webform
https://longwoodgardens.org/education/k-12-programs/teen-volunteer-program/apply

**Comment by maxfenton** [comment]
Assigning to @pingevt to triage where on the admin side there are style issues that make some admin actions un-see-able
