### ISSUE TITLE
Paragraph Library

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/longwood-d8#451]
Google Table Comment from Lynn:
Is there a way to name all reusable paragraphs that are promoted to the library? For example, sidebar boxes created within a flex page do not have a title field, and appear in the paragraph library as the first line of text from the sidebar box.

When browsing the paragraph library, the "Used" column seems to list the number of times a paragraph is used. But clicking on that number only shows 1 instance of use—or does the number in the column have a different meaning?

**Comment by pingevt** [comment]
When promoting a Paragraph, the label is auto-populated from content from within the para. This can be edited later, or right after promoting.

The use count might be a little behind if you are doing a lot of content entry and editing. However, it also counts the revisions.

**Comment by BSBaker2** [comment]
google table updated
