### ISSUE TITLE
feedback: sidebar spacing

### ISSUE THREAD

**Issue by maxfenton** [bluecadet/longwood-d8#454]
Google Table Comment from Lynn:

> Also, it appears that only one approved paragraph type can sit next to a sidebar at the moment. If the sidebar is longer than the paragraph, there is white space between the first and second paragraphs.

![Screen Shot 2022-03-28 at 10.52.05 AM.png](https://images.zenhubusercontent.com/5a6633b54b5806bc2bc3c84d/5a14717d-8399-4a5d-8327-1361186ff944)

**Comment by BSBaker2** [comment]
google table updated
