### ISSUE TITLE
WYSIWYG with Links issue

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/longwood-d8#457]
Google Table Comment from Lynn:
Why does the "WYSIWYG with Links" paragraph type have a header field, but the "WYSIWYG [without links]" does not?

Also, it seems that the "WYSIWYG with Links" paragraph is a good way to add an anchor to a flex page. Is there a preferred way that I might be missing?

https://live-longwood-d8-cms.pantheonsite.io/lg-test-flex-styles

**Comment by pingevt** [comment]
The  "WYSIWYG with Links" paragraph came out of the migration and was just an easier way to handle that. IN the WYSIWYG, you can just use an h2 tag for the header.

You can create an anchor in any full WYSIWYG by using hte button near the links that looks like a Flag.

**Comment by BSBaker2** [comment]
google table updated
