### ISSUE TITLE
Hide legacy ticket buttons on past events

### ISSUE THREAD

**Issue by BSBaker2** [bluecadet/longwood-d8#461]
Google Table comment from Jen: 

> On events that have no upcoming event dates, the tickets buttons should be suppressed/not show on the front end

https://migcheck-longwood-d8-cms.pantheonsite.io/events-performances/events/balletx-performance

**Comment by pingevt** [comment]
@BSBaker2 - this is weird and terrible... but migration, am I right!?

their "looks like this event has occurred" banner injects this:

```
<style>
#node-event-full-group-right .btn.ticket {
    display: none;
}
</style>
```

**Comment by maxfenton** [comment]
@pingevt I can add this to `past-events.twig`
```
{# Legacy kludge #}
<style>
  [data-section="sidebar_right"] .btn.ticket {
    display: none;
  }
</style>
```

and/or if you put a `is-past-event` flag in the body classes, I can write it into the universal CSS

**Comment by maxfenton** [comment]
Oh wait. We ended up running this through `c-banner-callout` not `c-past-events` anyway. So that won't work

**Comment by maxfenton** [comment]
devcomplete

**Comment by maxfenton** [comment]
Looks right on the example link.

**Comment by BSBaker2** [comment]
google table updated
